### ISSUE TITLE
感谢老哥，我这有coderwhy的vue3+ts，如果需要可以免费分享

### ISSUE THREAD

**Issue by bia2000** [Hacker-C/mall#1]

**Comment by Hacker-C** [comment]
> 

好的，哈哈

**Comment by bia2000** [comment]
链接：https://pan.baidu.com/s/1q9xSZQUV8ikEEiPwx7WCzw 
提取码：krf0

**Comment by bia2000** [comment]
还有个小程序的，不是B站上的
链接：https://pan.baidu.com/s/1p_eMjoKp6HxrA60qeo67jQ 
提取码：9b4r
